Repository OCA/OCB, pull requests merged in 2021-01, with the labels that each got.

#993 [9.0][FIX] CVE-2019-11782, portal: internal & portal groups are largely exclusive
  addons/portal/wizard/portal_wizard.py
Labels: approved

#994 [8.0][FIX] CVE-2019-11782, portal: internal & portal groups are largely exclusive
  addons/portal/wizard/portal_wizard.py
Labels: approved

#992 [10.0][FIX] CVE-2019-11782, portal: internal & portal groups are largely exclusive
  addons/portal/wizard/portal_wizard.py
Labels: approved

#987 [9.0][FIX] CVE-2019-11783, mail: make the current user member of the created channel
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
Labels: approved, security

#986 [10.0][FIX] CVE-2019-11783, mail: make the current user member of the created channel
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
Labels: approved, security

#980 [8.0][FIX] CVE-2019-11785, mail: better error reporting to follow
  addons/mail/mail_followers.py
Labels: approved, security

#979 [9.0][FIX] CVE-2019-11785, mail: better error reporting to follow
  addons/mail/models/mail_followers.py
Labels: approved, security

#976 [10.0][FIX] CVE-2019-11785, mail: better error reporting to follow
  addons/mail/models/mail_followers.py
Labels: approved, security

#964 [10.0][FIX] CVE-2018-15632, loading: require install mode to trigger db init
  odoo/cli/server.py
  odoo/cli/start.py
  odoo/modules/loading.py
Labels: security

#965 [9.0][FIX] CVE-2018-15632, loading: require install mode to trigger db init
  openerp/cli/server.py
  openerp/cli/start.py
  openerp/modules/loading.py
Labels: security

#966 [8.0][FIX] CVE-2018-15632, loading: require install mode to trigger db init
  openerp/cli/start.py
  openerp/modules/loading.py
Labels: security

#968 [10.0][FIX] CVE-2018-15633, document: escape before incrementing
  addons/web/static/src/js/widgets/sidebar.js
Labels: security

#969 [9.0][FIX] CVE-2018-15633, document: escape before incrementing
  addons/web/static/src/js/widgets/sidebar.js
Labels: security

#970 [8.0] [FIX] CVE-2018-15633, document: escape before incrementing
  addons/web/static/src/js/views.js
Labels: security

#971 [10.0][FIX] CVE-2018-15634, core: broken symbols on upload
  addons/web/controllers/main.py
Labels: security

#972 [9.0][FIX] CVE-2018-15634, core: broken symbols on upload
  addons/web/controllers/main.py
Labels: security

#973 [8.0][FIX] CVE-2018-15634, core: broken symbols on upload
  addons/web/controllers/main.py
Labels: security

#974 [10.0][FIX] CVE-2018-15638, mail: use consistent placeholder
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/chat_manager.js
  addons/mail/static/src/js/client_action.js
Labels: security

#975 [9.0][FIX] CVE-2018-15638, mail: use consistent placeholder
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/chat_manager.js
  addons/mail/static/src/js/client_action.js
Labels: security

#977 [9.0][IMP] CVE-2018-15645, mail: only delegate tracking during cron
  addons/mail/models/mail_thread.py
Labels: security

#978 [10.0][IMP] CVE-2018-15645, mail: only delegate tracking during cron
  addons/mail/models/mail_thread.py
Labels: security

#981 [10.0][FIX] CVE-2020-29396, base: make datetime coherent with dateutil
  addons/mail/models/mail_template.py
  odoo/addons/base/ir/ir_actions.py
  odoo/addons/base/ir/ir_qweb/qweb.py
  odoo/tools/misc.py
  odoo/tools/safe_eval.py
Labels: security

#982 [9.0][FIX] CVE-2020-29396, base: make datetime coherent with dateutil
  addons/mail/models/mail_template.py
  openerp/addons/base/ir/ir_actions.py
  openerp/tools/misc.py
  openerp/tools/safe_eval.py
Labels: security

#983 [8.0][FIX] CVE-2020-29396, base: make datetime coherent with dateutil
  addons/email_template/email_template.py
  openerp/addons/base/ir/ir_actions.py
  openerp/tools/misc.py
  openerp/tools/safe_eval.py
Labels: security

#984 [10.0][FIX] CVE-2019-11781, portal: backport of cc1e8f28
  addons/website_portal/controllers/main.py
Labels: security

#985 [9.0][FIX] CVE-2019-11781, portal: backport of cc1e8f28
  addons/website_portal/controllers/main.py
Labels: security

#988 [10.0][FIX] CVE-2019-11784, mail: don't self-notify
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_notification.py
Labels: security

#989 [9.0][FIX] CVE-2019-11786, base: load a language only when necessary
  openerp/addons/base/module/wizard/base_import_language.py
  openerp/addons/base/res/res_lang.py
Labels: security

#990 [8.0][FIX] CVE-2019-11786, base: load a language only when necessary
  openerp/addons/base/module/wizard/base_import_language.py
  openerp/addons/base/res/res_lang.py
Labels: security

#991 [10.0][FIX] CVE-2019-11786, base: load a language only when necessary
  odoo/addons/base/module/wizard/base_import_language.py
Labels: security
