Repository OCA/OCB, pull requests merged in 2022-01, with the labels that each got.

#1065 [BCP][11.0] [FIX] base: prevent messing up existing registry
  odoo/modules/registry.py
Labels: approved

#1097 [BCP][8.0] [IMP] base: restrict the authorized assets
  openerp/addons/base/ir/ir_qweb.py
Labels: approved

#1066 [BCP][11.0] [IMP] avoid cycle on request
  addons/web/controllers/main.py
  addons/website/models/website.py
  odoo/http.py
Labels: approved

#1083 [BCP][10.0] [IMP] avoid cycle on request
  addons/report/controllers/main.py
  addons/web/controllers/main.py
  addons/website/models/website.py
  odoo/http.py
Labels: approved

#1106 [BCP][FIX] web: more reliably avoid downloads on new file
  addons/web/static/src/js/views/form_widgets.js
Labels: approved, security

#1100 [BCP][11.0] [FIX] website: fix video loading
  addons/website/static/src/js/content/snippets.animation.js
Labels: approved, security

#1102 [BCP][9.0] [FIX] web_editor: video loading
  addons/web_editor/static/src/js/widgets.js
Labels: help wanted, work in progress, security

#1101 [BCP][10.0] [FIX] website: fix video loading
  addons/web_editor/static/src/js/widgets.js
Labels: help wanted, work in progress, approved, security

#1103 [BCP][8.0] [FIX] website: video loading
  addons/website/static/src/js/website.editor.js
Labels: help wanted, work in progress, security

#1096 [BCP][8.0] [FIX] web: expect explicit sign up parameters
  addons/auth_signup/controllers/main.py
  addons/web/controllers/main.py
Labels: approved

#1095 [BCP][9.0] [FIX] web: expect explicit sign up parameters
  addons/auth_signup/controllers/main.py
  addons/web/controllers/main.py
Labels: approved, security

#1094 [BCP][10.0] [FIX] web: expect explicit sign up parameters
  addons/auth_signup/controllers/main.py
  addons/web/controllers/main.py
Labels: approved, security

#1093 [BCP][11.0] [FIX] web: expect explicit sign up parameters
  addons/auth_signup/controllers/main.py
  addons/web/controllers/main.py
Labels: approved, security

#1087 [BCP][10.0] [FIX] base: prevent messing up existing registry
  odoo/modules/registry.py
Labels: approved, security

#1089 [BCP][9.0] [FIX] base: prevent messing up existing registry
  openerp/modules/registry.py
Labels: approved, security

#1090 [BCP][8.0] [FIX] base: prevent messing up existing registry
  openerp/modules/registry.py
Labels: approved, security

#1091 [BCP][7.0] [FIX] base: prevent messing up existing registry
  openerp/modules/registry.py
Labels: approved, security

#1073 [BCP][11.0] [IMP] website_mail: optimise nonsense subscription
  addons/website_mail/controllers/main.py
Labels: approved

#1079 [9.0][BKP][IMP] website_mail: optimise nonsense subscription
  addons/website_mail/controllers/main.py
Labels: approved

#1080 [8.0][BKP][IMP] website_mail: optimise nonsense subscription
  addons/website_mail/controllers/main.py
Labels: approved

#1098 [BCP][9.0] [IMP] avoid cycle on request
  addons/report/controllers/main.py
  addons/web/controllers/main.py
  addons/website/models/website.py
  openerp/http.py
Labels: approved

#1104 [BCP][7.0] [IMP] avoid cycle on request
  addons/web/controllers/main.py
  addons/web/http.py
Labels: approved
